name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --verbose --release --target=x86_64-pc-windows-gnu
        use-cross: true
    - name: Output
      uses: actions/upload-artifact@v2
      with:
        name: out.exe
        path: ./target/x86_64-pc-windows-gnu/release/test-actions-rust-cross.exe
