name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust

    steps:
      - uses: actions/checkout@v2
      - name: Setup mingw
        run: >
          export DEBIAN_FRONTEND=noninteractive
          && apt-get update
          && apt-get install --no-install-recommends -y
          mingw-w64
          && rustup target add i686-pc-windows-gnu
      - name: Build
        run: cargo build --verbose --release --target=i686-pc-windows-gnu
      - name: Output
        uses: actions/upload-artifact@v2
        with:
          name: out.exe
          path: ./target/i686-pc-windows-gnu/release/test-actions-rust-cross.exe
